name: flutter_great_places
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  image_picker: ^0.8.7
  path_provider: ^2.0.13
  path: ^1.8.2
  sqflite: ^2.0.0+4
  location: ^4.4.0
  flutter_osm_plugin: ^0.51.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true